[package]
name = "writedisk"
version = "1.0.2"
authors = ["Nicholas Bishop <nbishop@neverware.com>"]
edition = "2018"
repository = "https://github.com/nicholasbishop/writedisk"
license = "Apache-2.0"
description = "Utility for writing to a disk image to a USB drive"
readme = "README.md"
keywords = ["disk", "usb", "image", "burn"]
default-run = "writedisk"

[dependencies]
progress = "0.2"
structopt = "0.3"
