[package]
name = "xtask"
version = "0.0.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
argh = "0.1"
camino = "1.0"
command-run = "1.0"
fehler = "1.0"
fs-err = "2.6"
rexpect = "0.4"
tempfile = "3.2"
